# Generated by Django 5.1.2 on 2024-11-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='precint_number',
            field=models.CharField(max_length=100),
        ),
    ]
