# Generated by Django 5.1.2 on 2024-11-11 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_precint_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='precint_number',
            new_name='precinct_number',
        ),
    ]
