# Generated by Django 5.1.3 on 2024-11-20 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
