# Generated by Django 5.1.3 on 2024-12-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
    ]
